Relation für Untergeordnete hinzugefügt
europace/partner-api pull request #31
Opened 2020-08-20 07:47 UTC by ollio

Rel für Untergeordnete in der API Spec ergänzt

https://europace.atlassian.net/jira/software/projects/PARTNER/boards/52?issueParent=16546&selectedIssue=PARTNER-218

2020-08-20 07:52 UTC, huehnerlady requested changes
Da wir die HAL Links abschaffen wollen sehe ich keinen Grund diesen Link hinzuzufügen

Siehe dazu auch [hier](https://github.com/europace/ep-apis/issues/76)

2020-08-20 07:57 UTC, gruenewa commented
Tja, ich bin jetzt auch etwas verwirrt ... machen wir jetzt kein HAL mehr?

2020-08-20 08:04 UTC, ollio commented
Ich bin jetzt noch verwirrter, was ist denn die Alternative? Einfach ein Konzept zu canceln ohne was neues finde ich schon komisch. Was soll ich denn jetzt machen? 
* Ein Attribut parentPartnerId?

2020-08-26 08:15 UTC, huehnerlady commented
@ollio ich nehme an dieser PR kann weg oder? 🤔

2020-08-26 08:16 UTC, closed without merging