Add Endpoint to set a Partnerkennzeichen
europace/partner-api pull request #45
Opened 2020-09-08 16:00 UTC by huehnerlady

Ich habe jetzt angenommen, dass die durch Hinzufügen eines neuen Endpunktes auf 2.1 hochgesetzt wird.

Bitte korrigiert mich, wenn ich falsch liege

2020-09-09 10:15 UTC, huehnerlady commented
Bitte reviewn aber nicht mergen, wir müssen erst noch den Bug beheben, ich merge dann

2020-09-09 11:23 UTC, gruenewa approved these changes
Ist für mich soweit okay :+1:

2020-09-15 06:50 UTC, ollio requested changes
Das Problem ist, dass man beim PATCH nicht unterscheiden kann zwischen löschen und ignorieren. Ein PATCH mit bshAkquisitionsWeg:null ist in JSON das gleiche, als wenn man es weg lässt. Heißt es denn dann, dass ich bshAkquisitionsWeg löschen will oder ignorieren? 
Klarer ist hier ebenfalls (meine Präferenz) Json-Patch zu nutzen und die Partnerkennzeichen per Operation zu ändern oder zu löschen. Vorteil der API es gibt nur einen einzigen PATCH Endpunkt

2020-09-15 06:59 UTC, huehnerlady commented
> Das Problem ist, dass man beim PATCH nicht unterscheiden kann zwischen löschen und ignorieren. Ein PATCH mit bshAkquisitionsWeg:null ist in JSON das gleiche, als wenn man es weg lässt. Heißt es denn dann, dass ich bshAkquisitionsWeg löschen will oder ignorieren?
> Klarer ist hier ebenfalls (meine Präferenz) Json-Patch zu nutzen und die Partnerkennzeichen per Operation zu ändern oder zu löschen. Vorteil der API es gibt nur einen einzigen PATCH Endpunkt

ok @ollio , dann setze ich dich auf die Karte und du kannst dich dann darum kümmern

2020-10-05 15:52 UTC, huehnerlady commented
Hier muss noch mehr Analyse betrieben werden

2020-10-05 15:52 UTC, closed without merging