API-Definition für Zugang anlegen ergänzt
europace/partner-api pull request #52
Opened 2021-01-20 09:32 UTC by MikeKrueger75

- Zugang (Get/Post) hinzugefügt
- Auth auf http/Bearer angepasst
- Error-Modell hinzugefügt
- Tags aufgeräumt
Durch die Benutzung von Stoplight, wurden einige Daten in Hochkomma gesetzt, was wahrscheinlich konformer ist.

Ich brauche bitte auch fachliches Feedback zum Design als SubRessource.
Ticket: https://europace.atlassian.net/browse/PARTNER-511

Vielen Dank fürs Review.

2021-01-20 10:43 UTC, gruenewa commented
Gefällt mir soweit sehr gut. :+1:  Was mir noch unklar ist:

- Was genau geben wir bei der GET Operation zurück, wenn die Plakette noch keinen Zugang hat?
- Beim POST würde ich auch einen 406 Fehler zurückgeben, wenn der Zugang bereits aktiviert ist, richtig?

2021-01-20 11:23 UTC, gruenewa commented
Die Implementierung des Status
- REGISTERED
- NO_USER_CREDENTIALS
- UNVERIFIED
macht eventuell Zusatzaufwand. Auch ist mir die Abgrenzung der verschiedenen Zustände nicht ganz klar. Ein Nutzer ohne verifizierten Zugang ist ja eigentlich auch registriert, richtig? Und ich bin mir nicht sicher, ob ich aktuell überhaupt an den Daten erkennen kann, ob ein Nutzer ein Passwort hinterlegt hat. Mindestens für SSO Nutzer dürfte das ja schon heute der Fall sein. Muss her erstmal im Code schauen, wie wir das heutzutage erkennen. TL;DR: eventuell kann man in einer ersten Version auf das Flag 'status' verzichten?

2021-01-20 12:47 UTC, gruenewa requested changes
Ich bräuchte noch Klärung bzgl. 


- Was genau geben wir bei der GET Operation zurück, wenn die Plakette noch keinen Zugang hat?
-  Beim POST würde ich auch einen 406 Fehler zurückgeben, wenn der Zugang bereits aktiviert ist, richtig?
- Mir sind die Elemente im Status Feld unklar. Hier ist zunächst zu karen, wie der Zustand in unseren Datenbank auf diesen Enum mappt

2021-01-20 14:52 UTC, MikeKrueger75 commented
> Ich bräuchte noch Klärung bzgl.
> 
> * Was genau geben wir bei der GET Operation zurück, wenn die Plakette noch keinen Zugang hat?
> * Beim POST würde ich auch einen 406 Fehler zurückgeben, wenn der Zugang bereits aktiviert ist, richtig?
> * Mir sind die Elemente im Status Feld unklar. Hier ist zunächst zu karen, wie der Zustand in unseren Datenbank auf diesen Enum mappt

* Wenn es keinen Zugang gibt, dann wird folgendes zurückgegeben:
``` json
{
  "partnerId": "SCR06",
  "benutzername": "",
  "status": "KEIN_ZUGANG",
  "identityProviderConfigURL": "https://api.europace.de/auth/.well-known/openid-configuration"
}
```
* Zur Fehlermeldung: ich habe den Case ergänzt, aber Fehlercode wäre 406 👍🏻 
* die Statuscodes habe ich auf unseren internen angepasst - diese sind sprechend und in der GUI nachvollziehbar

2021-01-20 14:59 UTC, gruenewa approved these changes
Für mich passt es soweit :+1:

2021-01-21 08:28 UTC, gruenewa commented on partner-api.yaml
> +          description: Internal Server Error
Nicht wirklich wichtig, aber 500er Fehler müssen wir nicht als Teil der SST dokumentieren. Diese sind ja bereits Teil des HTTP Protokolls. In der Service Definition sollten fachliche Fehler dokumentiert werden. Ich würde diesen Part löschen.

2021-01-21 08:44 UTC, gruenewa commented on partner-api.yaml
> +                    statusCode: 406
Nur eine Verständnisfrage: Warum kodieren wir den HTTP Status-Code noch zusätzlich im Json. Habe ich schon häufiger gesehen, aber was ist der Grund/Vorteil?

2021-01-21 09:08 UTC, caspii commented
Ich finde es gut!

Verständnisfrage: sehe ich es richtig das mit der neuen API gar keine Plaketten bisher angelegt werden können?

Die Enums
```
KEIN_ZUGANG("Kein Zugang"),
ZUGANG_UNBESTAETIGT("Zugang noch nicht bestätigt"),
ZUGANG_REGISTRIERT("Registriert"),
ZUGANG_REGISTRIERT_KEIN_ZUGANG("Kein Zugang"),
BENUTZERNAME_AENDERUNG_UNBESTAETIGT("Änderung des Benutzernamens noch nicht bestätigt");
```
hätte ich anders benannt aber sind ja scheinbar schon festgelegt.

2021-01-21 09:08 UTC, caspii approved these changes

2021-01-21 09:08 UTC, caspii commented on partner-api.yaml
> +      summary: Your GET endpoint
Hier fehlt noch eine Summary

2021-01-21 16:15 UTC, gruenewa commented on partner-api.yaml
> +                    message: Username not allowed
Was genau unterscheidet die Felder `message` und `statusMessage`. Offenbar ist `message` die Kurzform und `statusMessage` ausführlich, aber brauchen wir das wirklich? Und warum steht eigentlich nicht in `message` die ausführliche Meldung und in `statusMessage` (analog zu `statusCode`) die Kurzform?

2021-01-25 15:49 UTC, gruenewa requested changes
Bei der Code-Generierung gibt es bei mir lokal Konflikte mit dem neu definiertem Error Typ. Es gibt bereits ein weiteres Objekt vom Typ Error(message, traceId) im Schema. Ich denke hier müssen wir beide Typen vereinheitlichen, oder?

2021-01-26 07:09 UTC, gruenewa commented
Ich habe mal alle Findings dieses PRs in https://github.com/europace/partner-api/pull/53 zum Review umgesetzt, so dass man die Changes mal sieht und vergleichen kann.

2021-01-26 08:25 UTC, closed without merging